### PR TITLE
Code cleanup

### LINKED ISSUE #31: Support for left icon
First of all thanks for the component, it has been useful for my use case. 
However, I noticed that there is no prop that allows me to put the icon on the left in the input. I read that the component's base is TextInput so I think it is possible.

### PR DESCRIPTION
**Pull request by Thodor12**
Revamped the entire documentation to better reflect all the properties, aswell as describe newly added properties.
Code changes to remove unnecessary properties, merged certain properties into objects, used proper typings where possible.

Property renames:
- `checkboxColor` -> `checkboxProps.checkboxColor`
- `checkboxUncheckedColor` -> `checkboxProps.checkboxUncheckedColor`
- `checkboxLabelStyle` -> `checkboxProps.checkboxLabelStyle`
- `checkboxLabelStyle` -> `checkboxProps.checkboxLabelStyle`
- `searchPlaceholder` -> `searchText`

Property type changes:
- `searchStyle` changed from custom object to ViewStyle
- `dialogStyle` changed from custom object to ViewStyle
- `theme` changed from custom object to ThemeProp (no effective change)

Other changes:
- `textInputMode` now defaults to "flat" to follow react-native-paper defaults
- "Select All" changed to "Select all"
- Error text now utilizes the MUI error theme instead of falling back to "red", unless overridden
- Theme now utilizes react native paper `useInternalTheme` to automatically grab the theme from the provider, giving the option to override the style on a per-component basis
- Styles have all been extracted to non-inline styles, except for the ones which rely on variables

No functionality should work differently after this PR, short of property changes, so it will be a breaking change.
Users may see differences in styling in some places (for example the defaulting to "flat", better respecting MUI theme, etc)

resolves #31

### CODE REVIEW

**Comment by Thodor12** [comment]
First finish #32 so changes can be merged into here

**Comment by srivastavaanurag79** [comment]
Please add the issue #31 feature needed i.e. the left icon prop in the text input. And thank you for your work.

**Comment by Thodor12** [comment]
@srivastavaanurag79 added that option too, could you look at #32 so I can merge that back into here?

**Comment by Thodor12** [comment]
Dialog label changes have been ported into here instead:

Currently it's not possible to separately style the close and done buttons.
In my application I'm consistently holding to a "error" style for cancel buttons and a "primary" style for completion/save buttons.
This is not doable if there's only 1 property available for setting the style for both buttons.

Suggested changes:
 - Introduce separate properties for the done and close buttons
 - Rename matching text properties to refer to "dialog" instead of "modal", to match other properties
 - Thanks to prettier some formatting related things have been changed (blame prettier)

**Comment by srivastavaanurag79** [comment]
Error: Unable to resolve module react-native-paper/lib/typescript/src/core/theming

**Comment by srivastavaanurag79** [comment]
did you remove the icon and everything?

**Comment by srivastavaanurag79** [comment]
can you please attach some screenshots as to what it looks like now ?

**Comment by srivastavaanurag79** [comment]
why have you wrapped it again inside a provider? people who would add react-native-paper will add there main app inside provider ?

**Comment by Thodor12** [comment]
> Error: Unable to resolve module react-native-paper/lib/typescript/src/core/theming

I pulled the repo and installed react-native-paper like normal, it could be there's a package update which prevents you from building it locally.

> did you remove the icon and everything?

Some properties have been moved to `textInputProps`, `checkboxProps` and `searchbarProps` as they don't warrant having to make a first class additional property.

> can you please attach some screenshots of what it looks like now?

Will do a bit later

> why have you wrapped it again inside a provider? people who would add react-native-paper will add their main app inside provider.

There's 2 different providers, PaperProvider and ThemeProvider. The first one is from react-native-paper themselves to supply the theme prop aswell as do other things underwater. ThemeProvider is the actual supply mechanism for the theme to MUI components. You can see that behaviour here: https://github.com/callstack/react-native-paper/blob/main/src/core/Provider.tsx

**Comment by srivastavaanurag79** [comment]
You changed a lot of things, and it isn't working in my system. It keeps throwing the error I sent you react-native-paper v5.5.1 is installed for me previously k was using v4.9.2

**Comment by Thodor12** [comment]
> You changed a lot of things, and it isn't working in my system. It keeps throwing the error I sent you react-native-paper v5.5.1 is installed for me previously I was using v4.9.2

My version is 5.5.1 too, could you maybe clean your node_modules? The import is correct, also:
> Will do a bit later, is there a way I can actually run the app locally. Is it possible to run the example using local version of the code?

**Comment by srivastavaanurag79** [comment]
> > You changed a lot of things, and it isn't working in my system. It keeps throwing the error I sent you react-native-paper v5.5.1 is installed for me previously I was using v4.9.2
> 
> My version is 5.5.1 too, could you maybe clean your node_modules? The import is correct, also:
> 
> > Will do a bit later, is there a way I can actually run the app locally. Is it possible to run the example using local version of the code?

I am running the local version of the example and the error still persists. Done clean install still same error:

Error: Unable to resolve module react-native-paper/lib/typescript/src/core/theming

`ThemeProvider can be imported directly from react-native-paper but the second import requires this path and its throwing error`

**Comment by Thodor12** [comment]
@srivastavaanurag79 I changed the imports and swapped `useInternalTheme` to `useTheme`. I cannot get the example to work on my local machine (it won't import the local changes to the package) so I am not able to actually check how it all works now

**Pull request merged**
